### ISSUE TITLE
Zephyr project template

### ISSUE THREAD

**Issue by VojislavM** [IRNAS/irnas-guidelines-docs#19]

**Comment by MarkoSagadin** [comment]
Things to do:
* follow Tjaz's advice above but:
    * dont add acitve object
    * add app_version as west module in west.yml
    * skip useful samples for now
    * dont add example sensor driver or dts
* structure of App folder should look like on of the recent projects. main.c should contain a hello world example.
* top level boards is a place for boards files and overlays that are used all over the project (app/samples) - check if we are currently correctly using this
* drivers folder can contain just empty kconfig and Cmakelist.txt
* add dts/bindings/.gitkeep just to have a place to start
* keep zephyr/module.yml as it is

**Comment by MarkoSagadin** [comment]
This was implemented in the `irnas-project-template` and `irnas-zephyr-template` repos, so this issue can be closed.
